SET C51INC=C:\Keil\C51\Inc;C:\Keil\C51\Inc\CMS8S6990
SET C51LIB=C:\Keil\C51\Lib
SET CPU_TYPE=CMS8S6990
SET CPU_VENDOR=Cmsemicon
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"C:\Keil\C51\BIN\C51.EXE" @".\PRO\init.__i"
"C:\Keil\C51\BIN\C51.EXE" @".\PRO\adc.__i"
"C:\Keil\C51\BIN\C51.EXE" @".\PRO\button.__i"
"C:\Keil\C51\BIN\C51.EXE" @".\PRO\vsp.__i"
"C:\Keil\C51\BIN\C51.EXE" @".\PRO\motor.__i"
"C:\Keil\C51\BIN\C51.EXE" @".\PRO\main.__i"
"C:\Keil\C51\BIN\C51.EXE" @".\PRO\flash.__i"
"C:\Keil\C51\BIN\C51.EXE" @".\PRO\uart.__i"
"C:\Keil\C51\BIN\BL51.EXE" @".\PRO\KCM363~1.LNP"
"C:\Keil\C51\BIN\OH51.EXE" ".\PRO\KCM363-25-10-11-²¦¶¯¿ª¹Ø" 
